### ISSUE TITLE
Inserting citation keeps cursor in 'citation editing mode'

### ISSUE THREAD

**Issue by floppywhisk** [zotero/zotero-libreoffice-integration#62] opened 2021-12-26 13:42 UTC
When you insert a citation, the cursor will stay within the citation box. That means you keep editing the citation with anything you type after it (except 'Enter').

Assuming you insert your citations on-the-fly while writing your paragraphs, this effectively hinders the workflow. You have to hit 'Enter' first, then write the rest of the sentence, and then delete the paragraph you had to insert between the citation and the following words to workaround your cursor being stuck in the citation.

A desirable default would be to have the citation inserted, and whatever you type after inserting the citation, not end up within the latter.

**Comment by dstillman** [comment] 2021-12-26 21:05
Please post support questions to the [Zotero Forums](https://forums.zotero.org), where we're best able to help.

This is a LibreOffice bug.

Duplicate of https://github.com/zotero/zotero-libreoffice-integration/issues/49

**Closed by dstillman** 2021-12-26 21:05 UTC
