### ISSUE TITLE
Bibliography does not follow section columns

### ISSUE THREAD

**Issue by fangly** [zotero/zotero-libreoffice-integration#12] opened 2014-01-22 03:22 UTC
In LibreOffice Writer, when editing a document that is formatted in two columns, any inserted Zotero bibliography ignores the columns and uses the entire page width. This behoaviour is seen when Zotero formats the document with ReferenceMarks. However, when using Bookmarks, the bibliography follows the column layou, as expected.

This issue has been encountered by several users: see https://forums.zotero.org/discussion/29185/insert-bibliography-doesnt-follow-section-columns-libreoffice/

My software versions are:
   Zotero Firefox addon 4.0.17.1
   Zotero LibreOffice integration 3.5.8
   LibreOffice 4.0.4.2

**Comment by seal20** [comment] 2015-02-21 06:42
Sorry I am not developer and I actually never contributed to zotero... I was just passing around. I cannot reproduce your bug. For me zotero keeps the column format even using References marks. Perhaps you could modified the page styles (Default style) and Paragraph style (Bibliography 1) that zotero use to keep your format. A little bit like this: https://www.zotero.org/support/kb/word_default_font
Sorry if it doesn't help you.

**Comment by fangly** [comment] 2015-03-23 07:50
I am now on:
   LibreOffice 4.2.7.2
   Zotero 4.0.26.1
   Zotero LibreOffice integration 3.5.9

The test files are not available anymore. However, I cannot seem to reproduce the bug anymore. It looks like it may have been fixed...

**Comment by ffsantos92** [comment] 2015-09-22 23:58
I'm experiencing the same issue.

***Reference marks (NOT OK)***:
![not_ok](https://cloud.githubusercontent.com/assets/8303937/10035047/f4929896-618d-11e5-9f77-c7d00f5c3f52.png)

***Bookmarks (OK)***:
![ok](https://cloud.githubusercontent.com/assets/8303937/10035070/21b30374-618e-11e5-97d8-0045a3465b02.png)

**Comment by crti** [comment] 2020-02-24 18:27
I'm also using a two column paper ODT template in Libre Office Writer and when using “Add/Edit Bibliography” like @fabiofdsantos a full page width new format style is inserted and I'm not able to easily bring that part back into the two column page layout. 
Beside this github page I found no Online resources about this issue and possible workarounds :-/

**Comment by adomasven** [comment] 2020-12-14 11:59
This seems to be gone in LibreOffice 7.0.3, so I'm closing it.

**Closed by adomasven** 2020-12-14 11:59 UTC
